const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
// const ERROR_DEFAULT = 500;
const OK = 200;
const ERROR_NOTAUTH = 401;
const CREATED = 201;
const ERROR_CONFLICT = 409;
const ERROR_NOTALLOWED = 403;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  // ERROR_DEFAULT,
  OK,
  ERROR_NOTAUTH,
  CREATED,
  ERROR_CONFLICT,
  ERROR_NOTALLOWED,
};
